config/routes.rb
KendoExamplesRails::Application.routes.draw do
  resources :expenses

  root :to => 'expenses#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>


<br />

<div id="grid"></div>

<script>
    $(document).ready(function () {
        var crudServiceBaseUrl = "/expenses",
            dataSource = new kendo.data.DataSource({
                transport: {
                    read:  {
                        url: crudServiceBaseUrl,
                        dataType: "json"
                    },
                    update: {
                        url: function(expense) {
                            return crudServiceBaseUrl + "/" + expense.id;
                        },
                        dataType: "json",
                        contentType: "application/json",
                        type: "PUT"
                    },
                    destroy: {
                        url: function(expense) {
                            return crudServiceBaseUrl + "/" + expense.id
                        },
                        dataType: "json",
                        type: "DELETE"
                    },
                    create: {
                        url: crudServiceBaseUrl,
                        dataType: "json",
                        contentType: "application/json",
                        type: "POST"
                    },
                    parameterMap: function(expense, type) {
                        if (type === "create" || type === "update") {
                            return JSON.stringify({ expense: expense });
                        }
                    }
                },
                pageSize: 30,
                schema: {
                    model: {
                        id: "id",
                        fields: {
                            title: { editable: true },
                            amount: { type: "number", validation: { required: true } }
                        }
                    }
                }
            });

        $("#grid").kendoGrid({
            dataSource: dataSource,
            navigatable: true,
            pageable: true,
            height: 400,
            toolbar: ["create", "save", "cancel"],
            columns: [
                { field: "title", width: "150px" },
                { field: "amount", format: "{0:c}", width: "150px" },
                { command: "destroy", title: " ", width: "110px" }],
            editable: true
        });
    });
</script>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @expense.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kendo and Ruby on Rails - Works Like a Charm</title>
    <%= stylesheet_link_tag "http://cdn.kendostatic.com/2012.1.322/styles/kendo.common.min.css",
      "http://cdn.kendostatic.com/2012.1.322/styles/kendo.default.min.css", :media => "all" %>
    <%= javascript_include_tag "application",
          "http://cdn.kendostatic.com/2012.1.322/js/kendo.all.min.js" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>